#-------------------------------
# General Site Settings

title: Brian Barr
description: Thinker // Designer // Citizen
email: brian.barr47@gmail.com

# NOTE: The Logo and Background image are defined in the all.sass document.

menu:
- {name: About Me, url: '#about-me'}
- {name: Work, url: '#work'}
- {name: Clients, url: '#clients'}
- {name: Contact, url: '#contact'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'The portfolio of Houston, TX based design student, Brian Barr.'
  rel-author: 'https://plus.google.com/u/1/+BrianBarrDesign/'
  rel-publisher: 'https://plus.google.com/u/1/+BrianBarrDesign/'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: UA-XXXXXX-X

#-------------------------------
# About Section

# NOTE: The avatar is defined in the all.sass document.

blurb: >
  **Brian specializes in making things** that bring communitites together.
  Most of the things he makes are [physical products](http://datadesignco.com){:target="_blank"},
  but he also puts effort into crafting [carefully written tunes](http://regenerationrecords.com){:target="_blank"}
  and [fixing bicycles](http://bikes.rice.edu){:target="_blank"}. Brian was born and raised in Atlanta, GA but is
  currently a junior at Rice University in Houston, TX studying Chemical Engineering. He finds design far more interesting.


skills:
- {name: Communication, value: '9'}
- {name: Organization, value: '7'}
- {name: Learning, value: '10'}
- {name: Rapid Prototyping, value: '8'}
- {name: Planning, value: '7'}
- {name: Visual Design, value: '5'}
- {name: Guitar Solos, value: '8'}
- {name: Bike Repair, value: '9'}

#-------------------------------
# Work Section

projects:
- {name: Three-Bike Bike Rack for METRO Buses, folder: 'proj-1', file: 'work/proj-1.html'}
- {name: The Coaster Campaign, folder: 'proj-2', file: 'work/proj-2.html'}
- {name: Voter Registration Jar Opener, folder: 'proj-3', file: 'work/proj-3.html'}
- {name: Sprawl Coasters, folder: 'proj-4', file: 'work/proj-4.html'}
- {name: Fed Up App, folder: 'proj-5', file: 'work/proj-5.html'}
- {name: Wide Awake Dreaming, folder: 'proj-6', file: 'work/proj-6.html'}
- {name: Georgia Tech Research Institute, folder: 'proj-7', file: 'work/proj-7.html'}
- {name: Rapid Protyping Projects, folder: 'proj-8', file: 'work/proj-8.html'}




#-------------------------------
# Clients Section

clients:
- {avatar: 'face-aaroni.jpg',
  name: 'Founder, Recording Artist',
  title: '2012 - Present, Atlanta, GA.',
  quote: "<p>Founded Regeneration Records, a non-profit record label that raises funds for cancer survivors.</p><p>Coordinated the release of two albums and three EPs, including writing, recording, and producing a personal solo album.</p>",
  logo: 'logo1.png'}
- {avatar: 'face-atariboy.jpg',
  name: 'General Manager',
  title: '2013 - Present, Houston, TX',
  quote: '<p>Grew student-run bike shop from 6 employees to 15 while growing revenue from $16,000 to $36,000 per year.</p><p>Managed a change in location and business model to ensure profitability and growth for years to come.</p><p>Built and repaired hundreds of bicycles per year as well as maintained a fleet of more than 35 rental bicycles.</p>',
  logo: 'logo2.png'}
- {avatar: 'face-jackiesaik.jpg',
  name: 'Summer Intern',
  title: '2014, Washington, DC',
  quote: '<p>Redesigned a portion of the EPA.gov site to increase accessibility and transparency of information.</p><p>Measured impact of US energy policy on deforestation rates using custom built Google Earth API Script.</p>',
  logo: 'logo3.png'}
- {avatar: 'face-teleject.jpg',
  name: 'Cleatus Cassidy',
  title: 'VP of Helmut, Lorem Sorem LLC.',
  quote: "<p>Partnered with the Leauge of Women Voters to use design to increase Houston's voter turnout rates.</p><p>Created a public opinion polling experience for Houston's disenfranchised populations.</p><p>Designed, prototyped, and tested a series of infographics on drink coasters to increase voter turnout.</p>",
  logo: 'logo4.png'}


#-------------------------------
# Contact Section

social:
- {icon: 'linkedin', link: 'https://www.linkedin.com/pub/brian-barr/99/3a2/687'}
- {icon: 'twitter', link: 'https://twitter.com/raising_thebarr'}
- {icon: 'soundcloud', link: 'https://soundcloud.com/regeneration-records'}
- {icon: 'instagram', link: 'https://instagram.com/brian.barr'}
#- {icon: 'linkedin', link: 'http://www.linkedin.com/in/travisneilson/'}


# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
