#-------------------------------
# General Site Settings

title: Brian Barr
description: Thinker // Designer // Citizen
email: brian@briancbarr.com

# NOTE: The Logo and Background image are defined in the all.sass document.

menu:
- {name: About Me, url: '#about-me'}
- {name: Portfolio, url: '#portfolio'}
- {name: Work Experience, url: '#work-experience'}
- {name: Contact, url: '#contact'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'The portfolio of Houston, TX based design student, Brian Barr.'
  rel-author: 'https://plus.google.com/u/1/+BrianBarrDesign/'
  rel-publisher: 'https://plus.google.com/u/1/+BrianBarrDesign/'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics-ua: UA-71179236-1

#-------------------------------
# About Section

# NOTE: The avatar is defined in the all.sass document.

blurb: >
  **Brian specializes in making things** that bring communities together.
  Most of the things he makes are [physical products](http://datadesignco.com){:target="_blank"},
  but he also puts effort into crafting carefully written tunes
  and [fixing bicycles](http://bikes.rice.edu){:target="_blank"}. Brian was born and raised in Atlanta, GA and is
  currently a senior at Rice University in Houston, TX studying Chemical Engineering. He finds design far more interesting.


skills:
- {name: Communication, value: '9'}
- {name: Curiosity, value: '7'}
- {name: Learning, value: '10'}
- {name: Rapid Prototyping, value: '8'}
- {name: Project Management, value: '7'}
- {name: Visual Design, value: '7'}
- {name: Guitar Solos, value: '8'}
- {name: Bike Repair, value: '9'}

#-------------------------------
# Work Section

projects:
- {name: Three-Bike Bike Rack for METRO Buses, folder: 'proj-1', file: 'work/proj-1.html'}
- {name: The Coaster Campaign, folder: 'proj-2', file: 'work/proj-2.html'}
- {name: Rice Bikes, folder: 'proj-3', file: 'work/proj-3.html'}
- {name: Sprawl Series Coasters, folder: 'proj-4', file: 'work/proj-4.html'}
- {name: Fed Up App, folder: 'proj-5', file: 'work/proj-5.html'}
- {name: Wide Awake Dreaming, folder: 'proj-6', file: 'work/proj-6.html'}
- {name: Georgia Tech Research Institute, folder: 'proj-7', file: 'work/proj-7.html'}
- {name: Rapid Prototyping Projects, folder: 'proj-8', file: 'work/proj-8.html'}




#-------------------------------
# Clients Section

clients:
- {avatar: 'face6.png',
  name: 'Cofounder, Designer',
  title: '2015 - Present | Houston, TX',
  quote: "<p>Founded a product design firm that creates data visualizations that double as homegoods.</p><p>Designed, prototyped, and negotiated rates with local manufacturers for production of three products to date.</p><p>Maintains a web presence that reaches hundreds of unique visitors per week.</p>",
  logo: 'logo6.png'}
- {avatar: 'face5.png',
  name: 'Design Intern',
  title: '2015 | Houston, TX',
  quote: "<p>Increased Houston's voter turnout rate by partnering with the League of Women Voters on a series of design projects.</p><p>Created a public opinion polling experience for Houston's disenfranchised populations.</p><p>Designed, prototyped, and tested a series of infographics on drink coasters to increase voter turnout.</p>",
  logo: 'logo5.png'}
- {avatar: 'face4.png',
  name: 'Summer Intern',
  title: '2014 | Washington, DC',
  quote: '<p>Redesigned a portion of the EPA.gov site to increase accessibility and transparency of information.</p><p>Measured impact of US energy policy on South American deforestation rates using custom built Google Earth API Script.</p>',
  logo: 'logo4.png'}
- {avatar: 'face3.png',
  name: 'General Manager',
  title: '2013 - Present | Houston, TX',
  quote: '<p>Expanded student-run bike shop from 6 employees to 15 while growing revenue from $16,000 to $36,000 per year.</p><p>Redesigned our business model and managed a change in location to ensure profitability and growth for years to come.</p><p>Built and repaired hundreds of bicycles per year as well as maintained a fleet of more than 35 rental bicycles.</p>',
  logo: 'logo3.png'}
- {avatar: 'face2.png',
  name: 'Founder, Recording Artist',
  title: '2012 - Present | Atlanta, GA.',
  quote: "<p>Founded Regeneration Records, a non-profit record label that raises funds for cancer survivors.</p><p>Coordinated the release of two albums and three EPs, including writing, recording, and producing a personal solo album.</p>",
  logo: 'logo2.png'}
- {avatar: 'face1.png',
  name: 'Research and Development Intern',
  title: '2011 - 2013 | Atlanta, GA.',
  quote: "<p>Experimentally determined the energy efficiency of vending machines for a large beverage company and recommended a series of improvements with the potential to save more than $76MM per year in energy costs.</p><p>Worked on a team to design a method for recycling phosphates from agricultural water pollutants back into fertilizers.</p><p>Designed and tested a novel photobioreactor for algal-based biofuels.</p>",
  logo: 'logo1.png'}

#-------------------------------
# Contact Section

social:
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/brian-barr-6873a299'}
- {icon: 'twitter', link: 'https://twitter.com/raising_thebarr'}
- {icon: 'soundcloud', link: 'https://soundcloud.com/regeneration-records'}
- {icon: 'instagram', link: 'https://instagram.com/brian.barr'}
#- {icon: 'linkedin', link: 'http://www.linkedin.com/in/travisneilson/'}


# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
